global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus сам себя мониторит
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Rust приложение
  - job_name: "trading-robot"
    static_configs:
      - targets: ["trading-robot:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  # ClickHouse
  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:8123"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # MongoDB
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]
    scrape_interval: 30s

  # PostgreSQL
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Kafka
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
    scrape_interval: 30s

  # Node Exporter (если добавим)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s


