apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    type: clickhouse
    access: proxy
    url: http://clickhouse:8123
    database: trading
    editable: true

dashboards:
  - name: Trading Robot Overview
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards/trading-overview.json

  - name: Database Performance
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards/database-performance.json

  - name: Trading Metrics
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards/trading-metrics.json

